### ISSUE TITLE
There is an error about javascript

### ISSUE THREAD

**Issue by yoosefi12** [Trembit/webrtc-showcase#1]
Hi 

I'm trying to run this application, but there is an error when I launch http://localhost:9000.
"Javascript is not enabled.". I read over the code "room.scala.html" and realized that all the script tags had been commented. could you possibly help me with it?

**Comment by cupuyc** [comment]
I migrated frontend from vanilla js to angular.
Now, one need to run via `ng server` or `ng build` (last in readme). I didn't run locally for a long time and don't remember exact steps.

**Comment by cupuyc** [comment]
Steps to run locally:
1st tab: `docker run --rm --name kms -p 8888:8888 kurento/kurento-media-server`
2nd tab: `sbt run`
3rd tab: `cd web` and `ng serve --host 0.0.0.0 -disable-host-check`
Visit: http://127.0.0.1:4200/room/someRoom


However, at the end, I wasn't able to see video in Firefox due to `ICE failed, add a TURN server and see about:webrtc for more details`. But it works in Chrome.

**Comment by yoosefi12** [comment]
It worked, Thanks a lot for helping.
